-- ===========================================================================
-- Swasti Homoeo Clinic — seed data
--
-- Generated by database/seed-builder.php from app/Content/FaqData.php.
-- Re-run that script after editing the bundled FAQ content.
--
-- Import AFTER database/schema.sql. Safe to import more than once: rows are
-- replaced rather than duplicated.
--
-- No administrator account is created here on purpose. Create one after import:
--   php -r "echo password_hash('your-strong-password', PASSWORD_DEFAULT), PHP_EOL;"
-- then paste the hash into the INSERT at the bottom of this file, or add the
-- user through the .env variables ADMIN_EMAIL and ADMIN_PASSWORD_HASH.
-- ===========================================================================

SET NAMES utf8mb4;
USE `swasti_homoeo`;

START TRANSACTION;

TRUNCATE TABLE `faqs`;

INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Where is Swasti Homoeo Clinic located?', 'The clinic is at Solar Colony, Solar Plant Road, above Bala Dental Clinic, opposite Tulasi’s Diagnostic Centre, Housing Colony, Bhathu Basti, Port Blair 744105. It is a few minutes from Garacharma. Call +91 79806 44867 or send a WhatsApp message and we will share the exact location pin as well.', 'About the clinic', 10, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Who treats patients at the clinic?', 'All consultations are conducted by Dr. Smriti Das, BHMS, MD (Homeopathy, WBUHS), the principal homoeopathic physician, with more than eight years of clinical experience. Registration particulars are displayed at the clinic and available on request.', 'About the clinic', 20, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Is homoeopathy safe without side effects?', 'Homoeopathic medicines are highly diluted and, when prescribed in the correct potency and dose, are generally very well tolerated. "No side effects" is not the right claim, though — some patients notice a temporary change in symptoms after starting a remedy, and the remedy must be chosen for the right person. The real risk is delaying necessary medical care, which is why we always tell you when a condition needs hospital treatment.', 'About the clinic', 30, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Do you accept insurance?', 'We currently provide treatment on a self-pay basis and issue a proper receipt for each consultation and remedy. For corporate or insurance reimbursement enquiries, please contact the clinic directly and we will tell you exactly what documentation we can issue.', 'About the clinic', 40, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('What are your consultation timings?', 'Monday to Friday the OPD runs from 10:00 AM to 7:00 PM with a break for lunch. Saturday is a morning OPD from 10:00 AM to 3:00 PM. Sunday is reserved for emergency calls only. Patients are always given a specific slot so the waiting time is short.', 'About the clinic', 50, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('How do I book a consultation?', 'Use the Book Consultation form on this website, call +91 79806 44867, or send a WhatsApp message to 91798 0644867 with your preferred day and time. We confirm your slot by phone or WhatsApp, usually the same day.', 'Booking and fees', 60, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Do I need a confirmed appointment, or can I walk in?', 'A confirmed appointment is strongly recommended because most patients are given a fixed slot. If you arrive without a booking we will fit you in at the next available gap, but you may have to wait.', 'Booking and fees', 70, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('What does a consultation cost, and is it inclusive of medicines?', 'The consultation fee is separate from the cost of the dispensed remedy, and the remedy cost depends on the potencies and quantities your prescription requires. Both figures are confirmed to you in writing before anything is dispensed, and a receipt is issued. Follow-up review fees are lower than a first consultation.', 'Booking and fees', 80, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Is a follow-up appointment necessary?', 'Yes. Homoeopathic prescribing depends on how your symptoms are responding, so review appointments let us continue an effective prescription, reduce it once things settle, or change it if it is not working. Most patients need two to four reviews before a meaningful judgement can be made.', 'Booking and fees', 90, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('What should I bring to my first appointment?', 'Bring a list of every medicine you are currently taking — including supplements — with the doses, any previous prescriptions or investigation reports, and a rough timeline of how your symptoms have changed. If you can note down when your periods or sleep patterns changed, that is genuinely useful to the doctor.', 'Booking and fees', 100, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Can I be treated over phone or WhatsApp?', 'An online or telephone discussion is fine for a brief follow-up, for reviewing a prescription you have already been given, and for general guidance. A first consultation requires an in-person visit so that you can be examined and a complete history taken.', 'Booking and fees', 110, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('How long does homoeopathic treatment take to show results?', 'It depends entirely on the condition. An acute complaint such as a cold or acidity flare may improve in a few days. A long-standing condition like chronic eczema or a decade of back pain usually needs two to six months of continuous treatment, reviewed at fixed intervals. We will give you a realistic timeline at your first visit rather than a hopeful one.', 'Treatment and results', 120, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('How many medicines will I be given?', 'Usually one remedy at a time. Prescribing several remedies together makes it impossible to know which one is helping, and classical homoeopathy works on a single individualised remedy. Occasionally a second remedy is used for a specific intercurrent complaint, and this is always explained.', 'Treatment and results', 130, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Can I stop my allopathic medicines once I feel better?', 'No. Do not stop, reduce or change any prescribed medicine without speaking to the doctor who prescribed it. In particular, insulin, blood-pressure and thyroid medicines, anti-epileptics, steroids and antibiotics must continue exactly as prescribed. Our aim is to work alongside your medical care, never to replace it unilaterally.', 'Treatment and results', 140, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('What should I avoid while taking treatment?', 'Take the remedy as prescribed, roughly half an hour away from meals, and avoid strong coffee, alcohol and very spicy or very oily food for the first few weeks. Do not rub the pills, keep them away from strong smells and camphor, and store the bottle tightly closed. Do not crush the pills to make them easier to swallow unless the doctor has told you to.', 'Treatment and results', 150, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Will homoeopathy work for my condition?', 'Ask us at your consultation and we will give you a direct answer. Some conditions respond well, some respond slowly, and a few need hospital care instead. We would rather tell you on the first day that homoeopathy is not the right tool for your problem than take your money and your time for six months.', 'Treatment and results', 160, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Can homoeopathy be given to infants and children?', 'Yes, with the correct potency and dose for the child’s age and sensitivity, and with the parent administering it rather than the child. A paediatric consultation takes longer because the history comes from you and every detail about feeding, sleep and behaviour matters.', 'For children and parents', 170, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Is homoeopathy safe during pregnancy?', 'It can be used under professional supervision once the pregnancy is confirmed by a qualified obstetrician. We will not prescribe during the first trimester except in exceptional circumstances, and we will always ask you to continue any medication your doctor has given you. Please bring your antenatal records to every visit.', 'For children and parents', 180, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Can I give my child a remedy from an earlier consultation?', 'Please do not. A remedy is matched to one child’s symptom picture, and an old prescription is often not the right one for a new illness. Bring the old bottle to the visit so the doctor can review what was given and why.', 'For children and parents', 190, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Does the clinic handle emergencies?', 'No. A homoeopathy clinic is not an emergency facility and we do not have the equipment, monitoring or surgical capability for one. For chest pain, breathing difficulty, sudden weakness, facial droop, heavy bleeding, loss of consciousness, a severe allergic reaction, a serious fall or a suspected poisoning, call 112 or go to the nearest emergency department immediately.', 'Emergencies and limits', 200, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Can homoeopathy replace antibiotics or surgery?', 'No. Where antibiotics, surgery or hospital care are clinically indicated, that is the treatment of choice and we will say so. Homoeopathy is used as complementary care: it can support recovery, manage recurrent tendencies and sometimes reduce repeat prescriptions, but it does not substitute for necessary medical intervention.', 'Emergencies and limits', 210, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Why is a homoeopathy doctor always asking about my whole lifestyle?', 'Because classical homoeopathy works on the whole person rather than on a single symptom. Your sleep, digestion, temperature preference, thirst, mood, what you crave and what you dread, your menstrual pattern and your family history are all part of the "totality" the remedy is matched to. That is why the first consultation takes 30 to 45 minutes while a follow-up takes ten.', 'Emergencies and limits', 220, 1, NOW(), NOW());
INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)
VALUES ('Do you offer home visits?', 'Home visits are not part of routine practice because proper prescribing needs examination and an undisturbed history. In special circumstances — for an elderly or bedridden patient travelling a long distance, for instance — contact the clinic and we will discuss what is possible and what the cost would be.', 'Emergencies and limits', 230, 1, NOW(), NOW());

COMMIT;

-- --------------------------------------------------------- admin account
-- Uncomment, replace the hash, then import again. Generate a hash with:
--   php -r "echo password_hash('your-strong-password', PASSWORD_DEFAULT);"
--
-- INSERT INTO `users` (`name`, `email`, `password_hash`, `role`, `is_active`)
-- VALUES ('Clinic Administrator', 'admin@swastihomeo.com', '$2y$10$REPLACE_ME', 'admin', 1);

