<?php
declare(strict_types=1);

/**
 * Regenerates database/seed.sql from the bundled content in app/Content.
 *
 *     php database/seed-builder.php
 *
 * Keeps the SQL import in step with FaqData.php so /admin/faqs starts with the
 * same questions the public FAQ page would show without a database. Run it
 * again after editing app/Content/FaqData.php.
 */

$root = dirname(__DIR__);

require $root . '/app/bootstrap.php';

use App\Content\FaqData;

/** Escape a string for a single-quoted MySQL literal. */
$quote = static function (string $value): string {
    return "'" . str_replace(
        ["\\", "'", "\n", "\r", "\x1a"],
        ["\\\\", "\\'", "\\n", "\\r", "\\Z"],
        $value
    ) . "'";
};

/** Collapse authored paragraphs into literal \n so answers stay readable. */
$answerSql = static function (string $answer) use ($quote): string {
    $answer = trim($answer);
    $answer = preg_replace('/\R{2,}/', "\n\n", $answer) ?? $answer;

    return $quote($answer);
};

$rows  = FaqData::all();
$lines = [];

$lines[] = '-- ===========================================================================';
$lines[] = '-- Swasti Homoeo Clinic — seed data';
$lines[] = '--';
$lines[] = '-- Generated by database/seed-builder.php from app/Content/FaqData.php.';
$lines[] = '-- Re-run that script after editing the bundled FAQ content.';
$lines[] = '--';
$lines[] = '-- Import AFTER database/schema.sql. Safe to import more than once: rows are';
$lines[] = '-- replaced rather than duplicated.';
$lines[] = '--';
$lines[] = '-- No administrator account is created here on purpose. Create one after import:';
$lines[] = '--   php -r "echo password_hash(\'your-strong-password\', PASSWORD_DEFAULT), PHP_EOL;"';
$lines[] = '-- then paste the hash into the INSERT at the bottom of this file, or add the';
$lines[] = '-- user through the .env variables ADMIN_EMAIL and ADMIN_PASSWORD_HASH.';
$lines[] = '-- ===========================================================================';
$lines[] = '';
$lines[] = 'SET NAMES utf8mb4;';
$lines[] = 'USE `swasti_homoeo`;';
$lines[] = '';
$lines[] = 'START TRANSACTION;';
$lines[] = '';
$lines[] = 'TRUNCATE TABLE `faqs`;';
$lines[] = '';

foreach ($rows as $row) {
    $lines[] = sprintf(
        "INSERT INTO `faqs` (`question`, `answer`, `category`, `sort_order`, `is_published`, `created_at`, `updated_at`)"
        . "\nVALUES (%s, %s, %s, %d, %d, NOW(), NOW());",
        $quote((string) $row['question']),
        $answerSql((string) $row['answer']),
        $quote((string) $row['category']),
        (int) $row['sort_order'],
        (int) $row['is_published']
    );
}

$lines[] = '';
$lines[] = 'COMMIT;';
$lines[] = '';
$lines[] = '-- --------------------------------------------------------- admin account';
$lines[] = '-- Uncomment, replace the hash, then import again. Generate a hash with:';
$lines[] = '--   php -r "echo password_hash(\'your-strong-password\', PASSWORD_DEFAULT);"';
$lines[] = '--';
$lines[] = '-- INSERT INTO `users` (`name`, `email`, `password_hash`, `role`, `is_active`)';
$lines[] = '-- VALUES (\'Clinic Administrator\', \'admin@swastihomeo.com\', \'$2y$10$REPLACE_ME\', \'admin\', 1);';
$lines[] = '';

$sql  = implode(PHP_EOL, $lines);
$file = __DIR__ . '/seed.sql';

if (file_put_contents($file, $sql . PHP_EOL) === false) {
    fwrite(STDERR, 'Could not write ' . $file . PHP_EOL);
    exit(1);
}

printf('Wrote %s (%d FAQ rows, %d bytes).', $file, count($rows), strlen($sql) + 1);
echo PHP_EOL;